version: "3.8"

services:
  mini-rest-api:
    build: .
    restart: always
    ports:
      - "4000:3000"
    env_file:
      - .env
    networks:
      app_network:
        aliases:
          - mini-rest-api

networks:
  app_network:
    external: true
